apiVersion: v1
kind: Service
metadata:
  name: zongzhan-frontend
  namespace: zongzhan
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: zongzhan-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zongzhan-frontend
  namespace: zongzhan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zongzhan-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: zongzhan-frontend
    spec:
      containers:
        - name: zongzhan-frontend
          image: hub.arctron.cn/zongzhan-frontend:${VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 40
            periodSeconds: 3
            successThreshold: 1
            httpGet:
              port: 80
              scheme: HTTP
              path: /health
            timeoutSeconds: 2
          startupProbe:
            failureThreshold: 20
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            httpGet:
              port: 80
              scheme: HTTP
              path: /health
            timeoutSeconds: 2
